services:
  - type: web
    name: void-ia-bot
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: "8440948227:AAEX6QjX5vxHk9QQsQNDtOO13Dzvdm38kKw"
      - key: ENVIRONMENT
        value: "production"
